### ISSUE TITLE
Misleading transaction time when in micro block

### ISSUE THREAD

**Issue by friedger** [hirosystems/explorer#885] opened 2022-10-07 13:06 UTC
**Describe the bug**
A time in the past is shown for transactions in micro blocks

The time does not makes sense as it looks like that the tx is executed at the already confirmed block, more precisely, that the clarity variable `block_height` is the height of the confirmed block. This is not true. 

**To Reproduce**
1. Go to https://explorer.stacks.co/transactions?chain=testnet
2. See timestamp on microblock

**Expected behavior**
Do not show a transaction time until the block with the block_height used during processing the transaction is confirmed on Bitcoin.

**Screenshots**
![image](https://user-images.githubusercontent.com/1449049/194559945-a13d279a-1c69-459e-b993-30857e136530.png)

**Comment by 314159265359879** [comment] 2022-11-20 20:10
So if one sends a transaction and gets caught in a microblock it can show on the explorer as confirmed 15 minutes ago even when it was send 1 minute ago. very strange indeed. A bit more context. 

**Describe the solution you'd like** 
1. If the microblock does not have a timestamp then do not show a timestamp. 
2. If you can show a timestamp of when the transaction was send, show that instead. 
3. As soon as the transaction is anchored show the timestamp of that block. 

**Describe alternatives you've considered**
Alternatively it could be left as it is. However users will rightly find it strange. jnapp18 says: _"...the explorer should be showing information that makes sense to the end user."_ 

Why do microblocks not have timestamp, could they be made to have them? probably a question for the stacks-blockchain team. 

**Additional context**
![image](https://user-images.githubusercontent.com/33360391/202923320-bf687c54-40e0-49d8-84ba-56dc37b5df2c.png)

![image](https://user-images.githubusercontent.com/33360391/202923340-71499206-cdfd-47e4-a5d0-3fa5bdf2ced6.png)

![image](https://user-images.githubusercontent.com/33360391/202923416-d2ea96fa-4a4c-4b4f-9629-541f0ebd8f3d.png)

**Comment by friedger** [comment] 2022-11-23 09:41
In this case the blockhash is shown as `0x` 
![image](https://user-images.githubusercontent.com/1449049/203514487-06617383-d35a-4624-85e7-52620c76a965.png)

It would be good to show something more user friendly.

**Comment by Jamil** [comment] 2022-12-02 09:04
This is a huge issue for us too, it creates a lot of confusion around blockchain state. Why does it show as "in anchor block" when it is in microblock? We're getting a lot of issues and complaints from users, and since microblocks are often not actually final, people are (rightly) concerned when a transaction confirms "in anchor" and then gets reorged and their transaction fails / get a different NFT ID than they initially expected.

Understood this can happen with an actual anchor block too, but it's exacerbated here. Until the APIs actually treat microblocks as first-class blocks and dapps can easily index microblock state, easily call read-only contracts at microblock state, and we have some better finality, this is a poor UX decision.

**Comment by friedger** [comment] 2022-12-09 21:08
I also see txs in micro-blocks that are shown as "anchor block" but the anchor block hash is 0x. This is so confusing.

**Comment by G1ne** [comment] 2022-12-10 11:24
Yep.  Same thing I'm getting all yesterday.  Transactions seem to confirm in anchor block almost as soon as they are broadcast.

Then when you check for the BTC hash, nothing.  After a few mins the transaction is added to BTC block and the hash appears, however still yet to be found on any BTC block explorer. (Memo pool does not show. Blockchain.com it does not exist and Blockcypher also finds no transaction).

A few mins later again and then it shows.

Whole time saying confirmed in anchor block on STX side.

Thanx Werner for dropping the link to this.🙏🏾

**Comment by jcatama** [comment] 2022-12-11 08:44
+1
This is also happening to me.

**Comment by markmhx** [comment] 2022-12-12 09:09
cc @andresgalante @chresko and @zone117x @rafaelcr in case it's an API-side issue

**Comment by Hero-Gamer** [comment] 2022-12-12 15:47
I can confirm I'm seeing the same issue, in Explorer confirmed as Anchor Block, on wallet side is displaying as if it is Microblock on the balance tab, under Activity page displaying as if it is anchor block confirmed. 
<img width="1130" alt="image" src="https://user-images.githubusercontent.com/92864860/207089641-32054d64-2986-4fac-bafd-eba865576653.png">

**Comment by JackNapolitano** [comment] 2022-12-12 23:38
@rafaelcr I believe it is an API issue:
take a look at the response of:

https://stacks-node-api.stacks.co/extended/v1/tx/0x2e61434f2bfa98dd4aba504836b13f3329be46a5244c1d8db0e6f5a7cf51acd2?event_offset=0&event_limit=100&unanchored=true

`{
  "tx_id": "0x2e61434f2bfa98dd4aba504836b13f3329be46a5244c1d8db0e6f5a7cf51acd2",
  "nonce": 676,
  "fee_rate": "3500",
  "sender_address": "SP2R3CHRAP1HE4M64X1NZXHZT41JG3XGNHJW4HX2W",
  "sponsored": false,
  "post_condition_mode": "deny",
  "post_conditions": [],
  "anchor_mode": "any",
  "is_unanchored": false,
  "block_hash": "0x",
  "parent_block_hash": "0xdfded07bb693850e7f2f42d11430471890767eb8e791fe05f5d3c4830b1c0b0c",
  "block_height": 86941,
  "burn_block_time": -1,
  "burn_block_time_iso": "",
  "parent_burn_block_time": 1670887714,
  "parent_burn_block_time_iso": "2022-12-12T23:28:34.000Z",
  "canonical": true,
  "tx_index": 3,
  "tx_status": "success",
  "tx_result": {
    "hex": "0x0703",
    "repr": "(ok true)"
  },
  "microblock_hash": "0xb7f32e25268c4d93a2d197a3130d9aa66170d7831b9d2111176d622db2ae7c2c",
  "microblock_sequence": 0,
  "microblock_canonical": true,
  "event_count": 1,
  "events": [
    {
      "event_index": 0,
      "event_type": "smart_contract_log",
      "tx_id": "0x2e61434f2bfa98dd4aba504836b13f3329be46a5244c1d8db0e6f5a7cf51acd2",
      "contract_log": {
        "contract_id": "SP176ZMV706NZGDDX8VSQRGMB7QN33BBDVZ6BMNHD.project-indigo-act1",
        "topic": "print",
        "value": {
          "hex": "0x0c0000000401610d0000000c6c6973742d696e2d757374780a636f6d6d697373696f6e06162bcf9762d5b90bc36dc1b4759b1727690f92ddd31f67616d6d612d77617374656c616e6465722d636f6d6d697373696f6e2d76330269640100000000000000000000000000000006057072696365010000000000000000000000022d0d8159",
          "repr": "(tuple (a \"list-in-ustx\") (commission 'SPNWZ5V2TPWGQGVDR6T7B6RQ4XMGZ4PXTEE0VQ0S.gamma-wastelander-commission-v3) (id u6) (price u9345794393))"
        }
      }
    }
  ],
  "execution_cost_read_count": 5,
  "execution_cost_read_length": 6831,
  "execution_cost_runtime": 35709,
  "execution_cost_write_count": 1,
  "execution_cost_write_length": 112,
  "tx_type": "contract_call",
  "contract_call": {
    "contract_id": "SP176ZMV706NZGDDX8VSQRGMB7QN33BBDVZ6BMNHD.project-indigo-act1",
    "function_name": "list-in-ustx",
    "function_signature": "(define-public (list-in-ustx (id uint) (price uint) (comm trait_reference)))",
    "function_args": [
      {
        "hex": "0x0100000000000000000000000000000006",
        "repr": "u6",
        "name": "id",
        "type": "uint"
      },
      {
        "hex": "0x010000000000000000000000022d0d8159",
        "repr": "u9345794393",
        "name": "price",
        "type": "uint"
      },
      {
        "hex": "0x06162bcf9762d5b90bc36dc1b4759b1727690f92ddd31f67616d6d612d77617374656c616e6465722d636f6d6d697373696f6e2d7633",
        "repr": "'SPNWZ5V2TPWGQGVDR6T7B6RQ4XMGZ4PXTEE0VQ0S.gamma-wastelander-commission-v3",
        "name": "comm",
        "type": "trait_reference"
      }
    ]
  }
}`
### vs
https://stacks-node-api.mainnet.stacks.co/extended/v1/tx/0x2e61434f2bfa98dd4aba504836b13f3329be46a5244c1d8db0e6f5a7cf51acd2
`{
  "tx_id": "0x2e61434f2bfa98dd4aba504836b13f3329be46a5244c1d8db0e6f5a7cf51acd2",
  "nonce": 676,
  "fee_rate": "3500",
  "sender_address": "SP2R3CHRAP1HE4M64X1NZXHZT41JG3XGNHJW4HX2W",
  "sponsored": false,
  "post_condition_mode": "deny",
  "post_conditions": [],
  "anchor_mode": "any",
  "tx_status": "pending",
  "receipt_time": 1670887491,
  "receipt_time_iso": "2022-12-12T23:24:51.000Z",
  "tx_type": "contract_call",
  "contract_call": {
    "contract_id": "SP176ZMV706NZGDDX8VSQRGMB7QN33BBDVZ6BMNHD.project-indigo-act1",
    "function_name": "list-in-ustx",
    "function_signature": "(define-public (list-in-ustx (id uint) (price uint) (comm trait_reference)))",
    "function_args": [
      {
        "hex": "0x0100000000000000000000000000000006",
        "repr": "u6",
        "name": "id",
        "type": "uint"
      },
      {
        "hex": "0x010000000000000000000000022d0d8159",
        "repr": "u9345794393",
        "name": "price",
        "type": "uint"
      },
      {
        "hex": "0x06162bcf9762d5b90bc36dc1b4759b1727690f92ddd31f67616d6d612d77617374656c616e6465722d636f6d6d697373696f6e2d7633",
        "repr": "'SPNWZ5V2TPWGQGVDR6T7B6RQ4XMGZ4PXTEE0VQ0S.gamma-wastelander-commission-v3",
        "name": "comm",
        "type": "trait_reference"
      }
    ]
  }
}`


It seems that when setting "unanchored=true" in the API calls, it is returning tx_status = success for all microblocked transactions.

**Comment by JackNapolitano** [comment] 2022-12-13 00:13
Follow up. I see that in the API code, is unanchored is being set to !dbTx.block_hash. But as we see in the response, the block_hash is not null, rather, it is `"block_hash": "0x",`
```
function parseDbAbstractTx(dbTx: DbTx, baseTx: BaseTransaction): AbstractTransaction {
  const abstractTx: AbstractTransaction = {
    ...baseTx,
    is_unanchored: !dbTx.block_hash,
    block_hash: dbTx.block_hash,
```

**Comment by rafaelcr** [comment] 2022-12-13 06:22
@JackNapolitano you're right, thanks for digging! I'll get on it ASAP

**Comment by rafaelcr** [comment] 2022-12-14 15:54
The API fix has been deployed:
https://stacks-node-api.testnet.stacks.co/extended/v1/tx/0x1abc7363e913cf735bafba2ce498e1b8437163773f92999aa179e88c966cc38f?unanchored
```json
{
  "tx_id": "0x1abc7363e913cf735bafba2ce498e1b8437163773f92999aa179e88c966cc38f",
  "nonce": 9,
  "fee_rate": "3000",
  "sender_address": "ST3DSBNTDCMJYZR0RGA55ATYYPV94K4H6HG73NKK8",
  "sponsored": false,
  "post_condition_mode": "allow",
  "post_conditions": [],
  "anchor_mode": "any",
  "is_unanchored": true,
  "block_hash": "0x",
```

**Comment by rafaelcr** [comment] 2022-12-14 17:10
I think the only thing left to fix would be in the Explorer side. If a transaction is in a microblock, it shouldn't display a block height or at least mark it as pending.

<img width="920" alt="Screenshot 2022-12-14 at 11 05 45" src="https://user-images.githubusercontent.com/216195/207660758-8337201f-4a45-4d05-96b4-5893aa14a789.png">

In this screenshot, the API returns the tx's block height as 89239 because that is the block where this tx *will be confirmed in the future* (remember the API was called with `unanchored=true`), but the current block height at that time is 89238. The timestamp displayed does correspond to block 89238 though.

Additionally, if a user clicks on that block height, they're taken to https://explorer.stacks.co/block/0x?chain=testnet which is invalid

cc @He1DAr

**Closed** 2022-12-20 14:52 UTC
Labels: Bug 🐛, P1 Bug 🚨

**Comment by 314159265359879** [comment] 2023-02-02 09:28
This is closed yet there are still issues popping up like this. How is that possible?

I believe the top label should show "in microblock" rather than "confirmed in anchorblock", what is causing this to pop up again?

https://discord.com/channels/621759717756370964/691807526118883418/1067935417342623818
![image](https://user-images.githubusercontent.com/33360391/216280720-5b867d24-02f8-47b9-a006-71718dcdfc4c.png)

[Muthu believes](https://discord.com/channels/621759717756370964/691807526118883418/1068147705521639575) the timing being in the past may have something to do with the fact that bitcoin miner clocks are allowed to be slightly off: https://twitter.com/bitcoin_minion/status/1618239701105905664

The reason I believe it is like this issue again is because I do not see a "Block hash" (0x) that is more in line with the earlier issue of a microblock confirmation instead of an actual anchor block confirmation. The time is also exactly the time of the "previous" anchor block. 

Brice also seems to think so:
![image](https://user-images.githubusercontent.com/33360391/216283022-c5aa51d1-175d-4e14-a88d-1d51e002b3d2.png)

I agree with Jason: "Yeah microblock should be a clear state not just an early representation of anchor block..." and I believe that is also what the Explorer intends to show. Is it possible some API/explorer server is running an old instance without this fix or is the fix not complete yet?
