### ISSUE TITLE
Fix execution of sandbox read-only functions

### ISSUE THREAD

**Issue by LNow** [hirosystems/explorer#504] opened 2021-08-04 19:24 UTC
Every now and then when I try to execute read-only function in sandbox it fails to do that and shows `Page not found` error.

Contracts that I call are correctly deployed. And functions returns static values.

**Comment by owenstrevor** [comment] 2021-08-05 02:47
This problem also just happened to me.

Went here: https://explorer.stacks.co/sandbox/contract-call?chain=mainnet
Pasted the contract address SP466FNC0P7JWTNM2R9T199QRZN1MYEDTAR0KP27.miamicoin-core-v1 and called get-mining-stats-at-block function with the number 24497

**Comment by psq** [comment] 2021-08-07 23:00
this is more like every time I try to use the sandbox...  Can't remember the last time it worked for me, unfortunately.

**Comment by aulneau** [comment] 2021-08-07 23:30
Yeah, sorry folks -- the sandbox was something I made to help out myself and other devs working leading up to the stacks 2.0 launch, and it has not seen much feature improvements/additions since then with our work being more focused on the wallets and primary explorer features. If the sandbox is or can be of use to you, or you'd like to see it improve, please do express that so we can potentially prioritize it against our other work 🙏

**Comment by psq** [comment] 2021-08-08 06:05
yeah, understandable it is not the highest priority, and probably for a limited audience.  when it worked, it was really cool and useful! which makes it event more frustrating when you can't use it.  we can get the info in other ways, but that's more involved...

maybe focus initially on the ability to call read only functions, with perhaps improved error reporting (even in raw form) so we can report more useful failures (the page missing loses all context I think)

**Comment by LNow** [comment] 2021-08-10 11:12
@markmhx POX, BNS, SP466FNC0P7JWTNM2R9T199QRZN1MYEDTAR0KP27.miamicoin-core-v1
Functions: all read-only function.

If I'm able to call `get-pox-info` in `POX` contract, I know I'll be able to call any other `read-only` function. But when if fails, I know that it will fail for all.

One thing I noticed yesterday is that it fails when requests to `stacks-node-api.stacks.co` are failing with error 400.
Below is sample request I saved a moment ago:
```
await fetch("https://stacks-node-api.stacks.co/v2/contracts/call-read/SP000000000000000000002Q6VF78/pox/get-pox-info", {
    "credentials": "omit",
    "headers": {
        "User-Agent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:90.0) Gecko/20100101 Firefox/90.0",
        "Accept": "*/*",
        "Accept-Language": "en-US,en;q=0.5",
        "Content-Type": "application/json",
        "x-hiro-product": "explorer",
        "x-hiro-version": "undefined",
        "Sec-Fetch-Dest": "empty",
        "Sec-Fetch-Mode": "cors",
        "Sec-Fetch-Site": "same-site",
        "Sec-GPC": "1"
    },
    "referrer": "https://explorer.stacks.co/",
    "body": "{\"arguments\":[]}",
    "method": "POST",
    "mode": "cors"
});
```

**Comment by fbwoolf** [comment] 2021-09-09 00:50
@aulneau been trying to reproduce these failures today but the read-only functions have been successful for me unless I fill in the form incorrectly. Would a good first step on this be to update the form inputs to use formik validations/errors? Not sure where to start on this when I can't reproduce the issue?

**Comment by LNow** [comment] 2021-09-09 09:42
Since you introduced microblocks every contract-call that I've made so far was successful.
Due to above I think this issue could be closed or you can put it on a side for another week or two to be 100% that it is no longer valid and then close it.

**Comment by markmhx** [comment] 2021-09-09 11:53
@owenstrevor @psq mind trying your sandbox calls again and confirming whether they work for you now?

**Comment by fbwoolf** [comment] 2021-09-09 14:28
Moving this into QA to retest.

**Comment by Eshwari007** [comment] 2021-09-09 14:50
Not able to reproduce the issue as @fbwoolf indicated.Will move it to QA Done and close it upon hearing back from @owenstrevor and @psq

**Comment by andresgalante** [comment] 2022-08-05 15:18
I'll close this issue since it looks solved. If it isn't please reopen it

**Closed by andresgalante** 2022-08-05 15:18 UTC
Labels: Bug 🐛, P2 Bug 🕷, sandbox
