### ISSUE TITLE
[Sandbox] Missing available function

### ISSUE THREAD

**Issue by friedger** [hirosystems/explorer#959] opened 2023-01-16 22:00 UTC
**Describe the bug**
The list of available functions is empty even though the deployed contract has one read-only function:
https://explorer.stacks.co/txid/0xaa43f87204b86e27cc39aa351b19e7907694094a14716d729a958346bc574eb1?chain=testnet&api=https://2-1-api.testnet.hiro.so

**Expected behavior**
Even though, the first deployment failed, the list of available functions should show the functions of the last correctly deployed contract.

**Screenshots**

![image](https://user-images.githubusercontent.com/1449049/212771799-aeca3a1a-28c2-4d34-98d8-9f8dc92b9aec.png)

**Additional context**
Using 2-1-api.testnet.hiro.so

**Comment by BowTiedDeployer** [comment] 2023-01-31 18:52
It does not display available functions because of the block problem. The block hash is `0x`. The transaction was not yet confirmed in a block, it will be part of the upcoming block which is 2903 but is not yet formed. 

Will submit an issue because the same happened to me. 
https://discord.com/channels/621759717756370964/911531946738339900/1067968815528415302

Note: it also happens on the now official https://explorer.stacks.co/ testnet, not only the 2-1-api.testnet.hiro.so one.

**Comment by BowTiedDeployer** [comment] 2023-01-31 18:56
When checking it on the official testnet it shows that all the deployments failed. No available functions in this case. https://explorer.stacks.co/txid/0xaa43f87204b86e27cc39aa351b19e7907694094a14716d729a958346bc574eb1?chain=testnet
![image](https://user-images.githubusercontent.com/93231870/215855377-aa88c6a8-7085-438a-9e65-aed5223d2a4e.png)

And on the testnet 2-1 it displays no transaction with that id even tho it shows the pop-up corresponding to it.
https://explorer.stacks.co/txid/0xaa43f87204b86e27cc39aa351b19e7907694094a14716d729a958346bc574eb1?chain=testnet&api=https://2-1-api.testnet.hiro.so
![image](https://user-images.githubusercontent.com/93231870/215855679-3ccffa79-97c0-4286-b86e-46015f632482.png)

**Comment by He1DAr** [comment] 2023-06-21 19:39
The abi returned for this contract is null
https://api.testnet.hiro.so/extended/v1/contract/ST21815DY1QZWV6NAPCDE54BMHE10WK8HB2QXBNDT.helper-stx-account?unanchored=true
<img width="446" alt="image" src="https://github.com/hirosystems/explorer/assets/97111756/1590f0ff-cd7b-4738-939f-7959d75e65e7">

**Comment by He1DAr** [comment] 2023-06-21 19:40
@zone117x could you please take a look when you have time?

**Comment by zone117x** [comment] 2023-06-22 17:44
https://api.testnet.hiro.so/extended/v1/tx/0xaa43f87204b86e27cc39aa351b19e7907694094a14716d729a958346bc574eb1

The tx failed so the contract is not instantiated.

**Comment by chresko** [comment] 2023-07-28 13:42
Should this be closed then?

**Closed** 2023-07-28 20:37 UTC
