### ISSUE TITLE
Not pasting the right address

### ISSUE THREAD

**Issue by Hero-Gamer** [hirosystems/explorer#1144] opened 2023-05-18 18:31 UTC
Copy paste address issue 

See this example, 
https://explorer.hiro.so/address/SP3AP6DRSQ6P4FETB5M33D082Q2ABGJW60MT6103Q?chain=mainnet

I try to use the copy button, but what it says on screen is different to what it actually copied/pasted. 
**What it should be: **SP3AP6DRSQ6P4FETB5M33D082Q2ABGJW60MT6103Q
**What it has copied/pasted in fact:** SPGZT0M8NGP0AHFADP8GYBS9K4AMVPWSG8EZZWKR
Odd

**Comment by harrybasra95** [comment] 2023-05-21 13:12
It's working for me @Hero-Gamer.

**Comment by andresgalante** [comment] 2023-05-28 15:49
I can't reproduce it either :( 

@Hero-Gamer thanks for reporting it, can you try again?

@harrybasra95 thanks for testing it 🙏 

I'll close the issue for now, please reopen it if it persists.

**Closed by andresgalante** 2023-05-28 15:49 UTC
