### ISSUE TITLE
Incorrect last executed nonce shown

### ISSUE THREAD

**Issue by bilalanees98** [hirosystems/explorer#878] opened 2022-10-04 05:51 UTC
**Describe the bug**
The last executed nonce shows that "This account hasn't executed a tx yet", but a transactioon is shown as confirmed in the tx list.

Transaction link: https://explorer.stacks.co/txid/0xa9692c362891cc4e544d5f5d64d338b25a7c82812f8a7428df3f0f23e7be76e8?chain=mainnet
Address : https://explorer.stacks.co/address/SP3B8F88PXZPFREFHEMFXHYWPDNH80117YX7KBTT6?chain=mainnet

**To Reproduce**
1. Go to 'https://explorer.stacks.co/address/SP3B8F88PXZPFREFHEMFXHYWPDNH80117YX7KBTT6?chain=mainnet'
2. Click on 'https://explorer.stacks.co/txid/0xa9692c362891cc4e544d5f5d64d338b25a7c82812f8a7428df3f0f23e7be76e8?chain=mainnet'

**Expected behavior**
Last executed nonce should be 0;

**Desktop (please complete the following information):**
 - Browser: chrome

**Comment by shamim-io** [comment] 2023-05-10 20:22
I see that the issue is not solved it. I would check the API response and try to solve the issue.

**Comment by shamim-io** [comment] 2023-05-16 20:00
@andresgalante I have solved this issue and raised a PR. Kindly review it. Thanks!

**Comment by andresgalante** [comment] 2023-06-20 01:10
Thanks @shamim-io 🎉 I'll close this issue

**Closed by andresgalante** 2023-06-20 01:10 UTC
