### ISSUE TITLE
Transactions displayed as confirmed before the block is anchored.

### ISSUE THREAD

**Issue by BowTiedDeployer** [hirosystems/explorer#982] opened 2023-01-31 19:10 UTC
**Describe the bug**
The block hash is 0x. The transaction was not yet confirmed in a block, it will be part of the upcoming block but is not yet formed. It displays as it happened, but the read-only calls are giving information as it did not. And on top of that, it can still fail after appearing `Confirmed in anchor block`.

Transaction ID 0x8c805a97bbf2fffc1bbfe9dda68ef751f7f055fee9f64e60899f373f248c97bf
Address 
Block#95808
Time stamp UTC+2 8:42:02 PM 1/31/2023 

**To Reproduce**
1. Call a function
2. Watch the function getting `Confirmed in anchor block` with the block hash `0x` and Block height=height_of_the_latest_block_confirmed+1
3. Try to use the information related to the fact that it is `Confirmed in anchor block` and not be able to 
- call read only returns values which were before confirming the block
- can't see functions of deployed SC because they in fact are not yet confirmed

**Screenshots**
![image](https://user-images.githubusercontent.com/93231870/215856719-2ae57300-acb1-4255-9c22-171f1cdd16ab.png)
![image](https://user-images.githubusercontent.com/93231870/215857584-483a4194-d4a0-45cb-a1f8-2427aa7f298a.png)
![image](https://user-images.githubusercontent.com/93231870/215857594-c86fa932-cb34-44a8-a4f1-7836574df8b9.png)

**Desktop (please complete the following information):**
 - OS: Mac Os 13, Ubuntu 22, Windows 10
 - Browser Chrome, Safari, Brave
 - Version official- testnet and 2-1-testnet
 https://explorer.stacks.co/txid/0x8c805a97bbf2fffc1bbfe9dda68ef751f7f055fee9f64e60899f373f248c97bf?chain=testnet
 https://explorer.stacks.co/txid/0xaa43f87204b86e27cc39aa351b19e7907694094a14716d729a958346bc574eb1?chain=testnet&api=https://2-1-api.testnet.hiro.so

**Additional context**
It also says `Confirmed in anchor block`  even if the transaction fails. https://github.com/hirosystems/explorer/issues/959

**Comment by FriendsFerdinand** [comment] 2023-02-23 18:58
It's still ongoing. Is this because of the transition towards 2.1?

**Comment by tycho1212** [comment] 2023-02-23 19:22
@He1DAr @BLuEScioN we also encountered this issue while working on Zest Protocol - it would be great if someone could have a look here 🙏

Essentially the explorer already shows the transaction as confirmed before the Hiro API does, which leads to poor user experience where our app shows the transaction as pending while the explorer shows the transaction as confirmed

**Comment by andresgalante** [comment] 2023-02-24 14:55
There was a related issue with the API that should be fixed now.

@tycho1212 would you mind checking if the problem persists, please?

**Comment by diwakergupta** [comment] 2023-02-24 15:06
> There was a related issue with the API that should be fixed now.

But has that change been deployed already?

**Comment by andresgalante** [comment] 2023-02-24 18:53
yes, it should be deployed

**Comment by tycho1212** [comment] 2023-02-26 18:50
Hi @andresgalante and @He1DAr - I just checked and unfortunately the issue persists.

I got another confirmation in an anchor block on the explorer before the Hiro API returns a confirmation in an anchor block

<img width="939" alt="Screenshot 2023-02-26 at 18 47 29" src="https://user-images.githubusercontent.com/32067484/221430560-a2c859c3-d06f-4f4e-b9f0-7a5e30e61357.png">

<img width="706" alt="Screenshot 2023-02-26 at 18 47 51" src="https://user-images.githubusercontent.com/32067484/221430561-a564fa39-94ad-4e8a-b1f2-cde1a595fa32.png">

**Comment by tycho1212** [comment] 2023-02-26 19:05
I also can't find the Stacks block anywhere that the explorer refers to

The link is broken
<img width="1347" alt="Screenshot 2023-02-26 at 19 04 31" src="https://user-images.githubusercontent.com/32067484/221431289-688a2df3-3e95-4926-9f22-bc99b7157ed4.png">

And I can't find the block on the Blocks page
<img width="1351" alt="Screenshot 2023-02-26 at 19 04 22" src="https://user-images.githubusercontent.com/32067484/221431308-7189f0c4-c2ec-4c92-8a01-ee55f1e1c035.png">

**Closed** 2023-02-28 19:26 UTC
