### ISSUE TITLE
Something went wrong error when returning to a tab with active search result. 

### ISSUE THREAD

**Issue by 314159265359879** [hirosystems/explorer#1013] opened 2023-02-27 13:28 UTC
**Describe the bug**
Page shows error
![image](https://user-images.githubusercontent.com/33360391/221575274-c704bb8f-c342-454a-8a2b-7fc2dbd70590.png)

![image](https://user-images.githubusercontent.com/33360391/221575314-49596ca3-1dc0-4606-8642-ebf9a8cb4621.png)

![image](https://user-images.githubusercontent.com/33360391/221575338-9bb42864-3546-43d2-a58e-60617c7888cc.png)

Transaction ID 
n.a.

**To Reproduce**
1. Go to a page for example: https://explorer.stacks.co/txid/0x839e8818e634a85463d917cd8d30157d514a606a7ced33f78a38c1bca4c222b3?chain=mainnet
2. Wait for some time, go to another tab, then return
3. Hover over search/ or click it
4. See error (sometimes)

**Expected behavior**
I expect to be able to fill in the next query for a search. 

**Screenshots**
If applicable, add screenshots or consol.log to help explain your problem.

**Desktop (please complete the following information):**
Windows 11 latest
Firefox latest

**Comment by He1DAr** [comment] 2023-02-28 19:25
@314159265359879 would you mind trying to replicate this again? we launched a few tx fixes that might've fixed it already.

**Comment by andresgalante** [comment] 2023-03-02 16:13
Werner: I'll close this issue for now since we believe it's fixed, and we couldn't reproduce it.

 @314159265359879 if you see it again, would you mind reopening it?

**Closed by andresgalante** 2023-03-02 16:13 UTC
