### ISSUE TITLE
Screen truncation in Explorer-Sandbox

### ISSUE THREAD

**Issue by Eshwari007** [hirosystems/explorer#498] opened 2021-07-28 21:52 UTC
<img width="1236" alt="Screen Shot 2021-07-28 at 5 50 09 PM" src="https://user-images.githubusercontent.com/38872890/127401022-72d45199-9779-4601-8c74-cd7d387f3f0f.png">
Environment:TestNet
URL:https://explorer-git-feat-microblocks-final-blockstack.vercel.app/sandbox/contract-call

Seems like the middle section in sandbox-explorer is truncated and is not able to navigate from left to right as there is no scroll from left to right.There is a scrol
<img width="1264" alt="Screen Shot 2021-07-28 at 5 47 07 PM" src="https://user-images.githubusercontent.com/38872890/127400967-23365b27-2d22-4aba-a805-acfb277d7376.png">
<img width="1240" alt="Screen Shot 2021-07-28 at 5 47 23 PM" src="https://user-images.githubusercontent.com/38872890/127400969-822621c7-9988-4e4e-9c19-be4c4662bc59.png">
l from top to bottom however.

**Comment by aulneau** [comment] 2021-07-28 21:53
I'd say this is out of scope for the microblocks PR, and should be fixed in a separate PR.

**Comment by Eshwari007** [comment] 2021-07-28 22:03
Would this be apt for https://github.com/blockstack/explorer/pull/469

**Comment by aulneau** [comment] 2021-07-28 22:04
> Would this be apt for #469

no, it should be a new, different PR

**Comment by markmhx** [comment] 2021-07-29 14:13
Is this more of an enhancement than a bug? Or is this a regression on expected formatting behavior?

**Comment by andresgalante** [comment] 2023-06-19 22:16
Thank you for opening this issue. I'll close it since there has been no recent activity.
If you still believe the issue is relevant, please feel free to reopen it.

**Closed by andresgalante** 2023-06-19 22:16 UTC
Labels: Bug 🐛, P4 Bug 🐜, sandbox
